### ISSUE TITLE
Corrupted images

### ISSUE THREAD

**Issue by KarellenX** [XBMC-Addons/resource.images.studios.coloured#13]
Report of corrupted images in v0.0.14 of the add-on.

https://forum.kodi.tv/showthread.php?tid=210069&pid=2821323#pid2821323

**Comment by ronie** [comment]
thx, it's been reported already and fixed last week.

https://github.com/XBMC-Addons/resource.images.studios.coloured/commit/0f0405282f5b96241deced953cd56264a096d974

**Comment by ronie** [comment]
oops, after reading the post i see there are a few others besides dreamworks.
i'll have a look.

**Comment by ronie** [comment]
https://github.com/XBMC-Addons/resource.images.studios.coloured/commit/9c6e73732850e05d51bbe8843199c04fc9008dff

**Comment by monisriz** [comment]
The Ladd Company is another one - not sure why this is happening though.. I think I uploaded all of these.. most of them are fine but some seem to have become corrupted. Could this be an issue during the packing of texture.xbt?

**Comment by ronie** [comment]
found the issue.. only 8-bit colour images are supported.
16-bit colour images will end up corrupted.

**Comment by monisriz** [comment]
Ok.. will try and see which of my uploads are 16-bit and fix/upload the ones with issues.. thanks

**Comment by ronie** [comment]
not really needed, i've already checked all of the images.

these are the ones that were 16-bit:
https://github.com/XBMC-Addons/resource.images.studios.coloured/commit/6200c7254e85fa81f5a9426fe3dd7a4fb93e0274

**Comment by monisriz** [comment]
I found another couple on my local that were showing as 16-bit in Photoshop.. I guess you fixed them earlier..

**Comment by ronie** [comment]
yup i did. i've double-checked that all images are 8-bit now.

**Comment by KarellenX** [comment]
@ronie 

Passing on the requirement that icons are 8-bit, a member seems to be having problems when converting to 8-bit.

Are there other requirements?

https://forum.kodi.tv/showthread.php?tid=230821&pid=2823824#pid2823824

**Comment by ronie** [comment]
yes :-)

see answer in the thread

**Comment by KarellenX** [comment]
Great, thanks.

Just a summary of requirements (a reminder for me)

- *.png file format
- 8-bit colour
- RGB colour profile
- 161x109 resolution
- Ensure logos are visible on both light and dark backgrounds, so add a black drop shadow or light glow as needed.

**Comment by monisriz** [comment]
Another point that might be useful for others creating logos is using small black drop shadow. I use the option in photoshop and it might be called something else in other software. This doesn’t affect logos with black background (e.g. aeon nox silvo) but it helps logo visibility on skins with lighter colors and makes logos more universal I guess.

**Comment by Slim1399** [comment]
![qatar_tv_logo_](https://user-images.githubusercontent.com/58898611/235682726-ce0ab539-4bae-42a3-a1e0-7cb5a57afc72.png)
And this for: Qatar TV
