### ISSUE TITLE
Missing Studio's

### ISSUE THREAD

**Issue by as280093** [XBMC-Addons/resource.images.studios.coloured#31]
- [Creators in Pack](https://en.wikipedia.org/wiki/Creators_in_Pack)
- [EMT Squared](https://en.wikipedia.org/wiki/EMT_Squared)
- [ENGI](https://en.wikipedia.org/wiki/ENGI)
- [MAPPA](https://en.wikipedia.org/wiki/MAPPA_(studio))
- [Science Saru](https://en.wikipedia.org/wiki/Science_Saru)
- [Fox Star Studios](https://en.wikipedia.org/wiki/Fox_Star_Studios)
- [UV Creations](https://en.wikipedia.org/wiki/UV_Creations)

**Comment by ronie** [comment]
feel free to add them
