### ISSUE TITLE
Logos Needed for HBOMax and YouTube

### ISSUE THREAD

**Issue by BigChubbz** [XBMC-Addons/resource.images.studios.coloured#42]
The TVDB considers the network with the first airdate to be the network of record, so YouTube will be listed as the network for a few shows forever.  I don't know what criteria they use to differentiate between HBO and HBOMax, but they do and are notoriously strict about making any changes once they have made a decision.

FYI, here are the shows that I've noticed with no network logo:

Cobra Kai - YouTube
Raised by Wolves - HBOMax

Thanks!

**Comment by KarellenX** [comment]
HBO Max already exists... https://github.com/XBMC-Addons/resource.images.studios.coloured/blob/master/resources/HBO%20Max.png

**Comment by BigChubbz** [comment]
Thanks for the quick reply! How do i get that over into my installation? Or must I have some other issue that is keeping it from displaying?

**Comment by KarellenX** [comment]
The logo and studio name must be an exact match. 
The logo is named **HBO Max** so the studio in your library must also be named **HBO Max**

If you have **HBOMax**, it won't work as the name is different.

Install the Metadata Editor from `Settings>Add-ons>Install from repository>Program add-ons>Metadata Editor` and then you can edit your studios.

There are a few YouTube logos also. 
Click on <>Code above
Click into Resources
Select Go to file
Then type in the studio name and you can check what is available and what is missing

**Comment by BigChubbz** [comment]
Thank you very much for taking the time to help me.  I've been bumbling around with this for the past two hours and managed to resolve the issue by doing the following:

1. Go [here](https://github.com/XBMC-Addons/resource.images.studios.coloured)
2. Click on green code button and choose "Download ZIP"
3. Launch Kodi
4. Uninstall Studio Icons - Coloured
5. Install the zip file downloaded in step 2 at `Settings>Add-ons>Install from zip file>`

The above steps solve the HBO Max issue.

Next:

1.  Go to `C:\Users\XXXX\AppData\Roaming\Kodi\addons\resource.images.studios.coloured\resources` and make a copy of `YouTube Red.png`
2. Rename that copy `YouTube.png`

Hopefully this will help someone else that finds their way here with the same problem.  Thanks again for your help.  Without your replies, I wouldn't have figured this out.
